<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EMS.Core\EMS.Core.csproj" />
    <ProjectReference Include="..\EMS.DI\EMS.DI.csproj" />
    <ProjectReference Include="..\EMS.Repository\EMS.Repository.csproj" />
  </ItemGroup>

</Project>
